[package]
name = "my-python-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_python_lib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.3", features = ["extension-module"] }
pyo3-stub-gen = { version = "0.6.0", default-features = false }
